name: Create DB backups by schedule

on:
  push:
    branches: ['main']
    #schedule:
        #- cron: '5 * * * *'

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        - uses: webfactory/ssh-agent@v0.8.0
          with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        - name: Create DB Dump
          run: | 
            ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }} -p ${{ secrets.SSH_PORT }} 'mdkir /home/${{ secrets.SSH_USER }}/apps/test' 
            # ssh -o StrictHostKeyChecking=no username@yourVPSserverIP 'pg_dump -U postgres -W -F t yourdbname >/path_to/db_backup.tar' 
        # - name: Clone Backup Repo
        #   run: | 
        #     git clone git@github.com:username/backup-repository.git 
        #     cp /path_to/db_backup.tar backup-repository/ 
        # - name: Push to Backup Repo
        #   run: | 
        #     cd backup-repository 
        #     git add . 
        #     git commit -m "DB Backup" 
        #     git push