name: Create DB backups by schedule

on:
  push:
    branches: ['main']
  schedule:
    - cron: '0 22 * * *'

jobs:
  backup:
    runs-on: ubuntu-latest
    env:
      WISHLIST: 'wishlist-db'
      PORTFOLIO: 'portfolio-db'
      PRINCESS: 'princess-db'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install MongoDB Database Tools
        run: |
          # https://www.mongodb.com/community/forums/t/how-can-i-install-mongodb-database-tools-on-github-actions/208006/2
          # https://www.mongodb.com/try/download/database-tools
          wget https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu2204-x86_64-100.9.3.deb
          sudo apt install ./mongodb-database-tools-*.deb
      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v3
        with:
          host: github.com
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Setup GIT config
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "Serhii Chernenko"
      - name: Clone repos
        run: |
          repos=('${{ env.PORTFOLIO }}' '${{ env.WISHLIST }}' '${{ env.PRINCESS }}')
          for repo in "${repos[@]}"
          do
            echo "Exporting collection: $collection"
            git clone git@github.com:serhii-chernenko/$repo.git
          done
      - name: Backup Portfolio collections
        working-directory: ${{ env.PORTFOLIO }}
        run: |
          collections=('admins' 'bios' 'certificates' 'contacts' 'cooperation' 'pages' 'projects' 'sessions' 'youtubes')
          for collection in "${collections[@]}"
          do
            echo "Exporting collection: $collection"
            mongoexport --uri ${{ secrets.PORTFOLIO_URI }} --collection $collection --type json --out $collection.json
          done
          if [[ `git diff HEAD --shortstat` != "" ]]; then
            git add --all
            git commit -m "new backup"
            git push origin main
          else
            echo "There are no changes to commit."
          fi
      - name: Backup Wishlist collections
        working-directory: ${{ env.WISHLIST }}
        run: |
          collections=('users' 'wishes' 'gives')
          for collection in "${collections[@]}"
          do
            echo "Exporting collection: $collection"
            mongoexport --uri ${{ secrets.WISHLIST_URI }} --collection $collection --type json --out $collection.json
          done
          if [[ `git diff HEAD --shortstat` != "" ]]; then
            git add --all
            git commit -m "new backup"
            git push origin main
          else
            echo "There are no changes to commit."
          fi
      - name: Backup Princess collections
        working-directory: ${{ env.PRINCESS }}
        run: |
          collections=('channels' 'players' 'scores' 'status')
          for collection in "${collections[@]}"
          do
            echo "Exporting collection: $collection"
            mongoexport --uri ${{ secrets.PRINCESS_URI }} --collection $collection --type json --out $collection.json
          done
          if [[ `git diff HEAD --shortstat` != "" ]]; then
            git add --all
            git commit -m "new backup"
            git push origin main
          else
            echo "There are no changes to commit."
          fi
