name: Create DB backups by schedule

on:
  push:
    branches: ['main']
    #schedule:
        #- cron: '5 * * * *'

jobs:
  backup:
    runs-on: ubuntu-latest
    env:
      WISHLIST: 'wishlist-db'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install mongosh
        run: |
          # https://www.mongodb.com/docs/mongodb-shell/install/
          sudo apt-get install gnupg
          wget -qO- https://www.mongodb.org/static/pgp/server-7.0.asc | sudo tee /etc/apt/trusted.gpg.d/server-7.0.asc
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-mongosh
          mongosh=$(mongosh --version)
          echo "Mongosh vesrsion is $mongosh"
      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v3
        with:
          host: github.com
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Clone repos
        run: |
          repos=('${{ env.WISHLIST }}')
          for repo in "${repos[@]}"
          do
            echo "Exporting collection: $collection"
            git clone git@github.com:serhii-chernenko/$repo.git
          done
      - name: Export Wishlist collections
        working-directory: ./${{ env.WISHLIST }}
        run: |
          mongosh=$(mongosh --version)
          echo "Mongosh vesrsion is $mongosh"

          collections=('users' 'wishes' 'gives')
          for collection in "${collections[@]}"
          do
            echo "Exporting collection: $collection"
            mongoexport --uri ${{ secrets.WISHLIST_URI }} --collection $collection --type json --out $collection.json
          done
      - name: Push Wishlist backup
        working-directory: ./${{ env.WISHLIST }}
        run: |
          git add --all
          git commit -m "new backup"
          git push origin main
      # - name: Clone Backup Repo
      #   run: | 
      #     git clone git@github.com:username/backup-repository.git 
      #     cp /path_to/db_backup.tar backup-repository/ 
      # - name: Push to Backup Repo
      #   run: | 
      #     cd backup-repository 
      #     git add . 
      #     git commit -m "DB Backup" 
      #     git push